sql:
  # AssessmentTypeRepository
  asmtType:
    findIdByCode: >-
      SELECT id FROM asmt_type WHERE code= :code

  # SubjectRepositoryImpl
  subject:
    findIdByName: >-
      SELECT id FROM subject WHERE name= :name

  # GradeRepositoryImpl
  grade:
    findIdByCode: >-
      SELECT id FROM grade WHERE code= :code

  # AssessmentRepository
  assessment:
    findIdByNaturalId: >-
      SELECT id FROM asmt WHERE natural_id= :natural_id

    create: >-
      INSERT INTO asmt (natural_id, grade_id,type_id, subject_id, school_year, name, label, version, import_id, update_import_id) VALUES
                       (:naturalId, :gradeId, :typeId, :subjectId, :schoolYear, :name, :label, :version, :import_id, :update_import_id)
    assessmentScore:
      create: >-
        INSERT INTO asmt_score (asmt_id, cut_point_1, cut_point_2, cut_point_3, min_score, max_score) SELECT (SELECT id FROM asmt WHERE natural_id=:asmtId), :cutPoint1, :cutPoint2, :cutPoint3, :minScore, :maxScore

  #ClaimRepository
  claim:
    findIdByCode: >-
      SELECT id FROM claim WHERE code= :code

  #DepthOfKnowledgeRepository
  dok:
    findIdByLevelAndSubject: >-
      SELECT id FROM depth_of_knowledge WHERE level= :level and subject_id = (SELECT id FROM subject WHERE name = :subjectName)

  #MathPracticeRepository
  mathPractice:
    findByPractice: >-
      SELECT practice FROM math_practice WHERE practice= :practice

  #TargetRepository
  target:
    findIdByCodeAndClaim: >-
      SELECT id FROM target WHERE code= :code AND claim_id = (SELECT id FROM claim WHERE code= :claimCode)

  # ItemRepository
  item:
    create: >-
      INSERT INTO item (asmt_id, claim_id, target_id, natural_id, math_practice, allow_calc, dok_id, difficulty, max_points)
                        select (select id as asmt_id from asmt where natural_id=:asmtId), :claimId, :targetId, :itemId, :mathPractice, :allowCalc, :dokId, :difficulty, :maxPoints

  # AccommodationRepository
  accommodation:
    findIdByCode: >-
      SELECT id FROM accommodation WHERE code= :code

    create: >-
      INSERT IGNORE INTO accommodation (code) VALUES (:code)

  # LanguageRepository
  language:
    findIdByCode: >-
      SELECT id FROM language WHERE code= :code

  # AccommodationTranslationRepository
  accommodationTranslation:
    create: >-
      INSERT INTO accommodation_translation (accommodation_id, language_id, label)
         SELECT (SELECT id AS accommodation_id FROM accommodation WHERE code = :accCode), :langId, :label
           ON DUPLICATE KEY UPDATE label=:label

    findByAccCodeAndLangCode: >-
      SELECT id FROM accommodation_translation WHERE accommodation_id=:accId AND language_id=:langId

    updateTranslation: >-
      UPDATE accommodation_translation SET label=:label WHERE accommodation_id=:accId AND language_id=:langId



