management:
  security:
    enabled: false

spring:
  cloud:
    stream:
      bindings:
        packageInput:
          destination: PACKAGE
          group: default
        codesInput:
          destination: CODES
          group: default

  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 20
    initialSize: 4
    maxWait: 10000

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false