# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  security:
    enabled: false
server:
  port: 8008
  tomcat:
    max-connections: 2
    max-threads: 2

# spring auto-configured aws defense
cloud:
  aws:
    # there must be a default region when running locally
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false
    credentials:
      instance-profile: false

# use LocalArchiveService by default
archive:
  root: file:///tmp/

spring:
  cloud:
    stream:
      bindings:
        codesInput:
          destination: CODES
          group: default
        organizationInput:
          destination: ORGANIZATION
          group: default
        packageInput:
          destination: PACKAGE
          group: default
        normsInput:
          destination: NORMS
          group: default
        subjectInput:
          destination: SUBJECT
          group: default

  profiles:
    include: ingest-common

  datasource:
    url: "\
      jdbc:mysql://${spring.datasource.url-server:localhost:3306}/${spring.datasource.url-schema:warehouse}\
      ?useSSL=${spring.datasource.use-ssl:false}\
      &useLegacyDatetimeCode=${spring.datasource.use-legacy-datetime-code:false}\
      &characterEncoding=${spring.datasource.character-encoding:utf8}\
      &rewriteBatchedStatements=${spring.datasource.rewrite-batched-statements:true}\
      &noAccessToProcedureBodies=${spring.datasource.no-access-to-procedure-bodies:true}\
      &connectTimeout=${spring.datasource.connect-timeout:10000}\
      &socketTimeout=${spring.datasource.socket-timeout:130000}\
      "
    jdbcInterceptors: "QueryTimeoutInterceptor(queryTimeout=${spring.datasource.query-timeout:120})"
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    validationQueryTimeout: 10000
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    initialSize: 4
    maxActive: 10
    minIdle: ${spring.datasource.initialSize}
    maxIdle: ${spring.datasource.maxActive}

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
