management:
  security:
    enabled: false
server:
  port: 8008
  tomcat:
    max-connections: 2
    max-threads: 2

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: GROUPS
          group: default

  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false&useLegacyDatetimeCode=false&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 10
    initialSize: 4

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
