management:
  security:
    enabled: false

# spring auto-configured aws defense
cloud:
  aws:
    # there must be a default region when running locally
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false
    credentials:
      instance-profile: false

# use LocalArchiveService by default
archive:
  root: file:///tmp/

server:
  port: 8008
  tomcat:
    max-connections: 2
    max-threads: 2

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: GROUPS
          group: default

  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false&useLegacyDatetimeCode=false&characterEncoding=utf8&rewriteBatchedStatements=true&sessionVariables=group_concat_max_len=10000
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 10
    initialSize: 4

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

