# docker-compose specs for rdw ingest processes with the configuration server and RabbitMQ
# running in containers and MySQL running natively (outside the containers).
#
# The following environment variables MUST be set before running this spec, for config server.
# CONFIG_SERVICE_REPO - git repo url, e.g. https://gitlab.com/fairwaytech/rdw_config.git
# GIT_USER - user with rights to access CONFIG_SERVICE_REPO
# GIT_PASSWORD - password for GIT_USER

version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  config-server:
    image: smarterbalanced/configuration-service:3.1.2-RELEASE
    container_name: config-server
    ports:
      - 8888:8888
    depends_on:
      - rabbitmq
    environment:
      - CONFIG_SERVICE_REPO
      - ENCRYPT_KEY
      - CONFIG_SERVICE_SEARCH_PATH=tenant*
      - GIT_USER
      - GIT_PASSWORD
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq:5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 10s
      timeout: 2s
      retries: 6

  import-service:
    image: smarterbalanced/rdw-ingest-import-service
    ports:
      - 8080:8080
      - 8081:8008
    volumes:
      - /tmp:/tmp
    links:
      - config-server
      - rabbitmq
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888

  exam-processor:
    image: smarterbalanced/rdw-ingest-exam-processor
    ports:
      - 8082:8008
    volumes:
      - /tmp:/tmp
    links:
      - config-server
      - rabbitmq
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq

  group-processor:
    image: smarterbalanced/rdw-ingest-group-processor
    ports:
      - 8086:8008
    volumes:
      - /tmp:/tmp
    links:
      - config-server
      - rabbitmq
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq

  package-processor:
    image: smarterbalanced/rdw-ingest-package-processor
    ports:
      - 8083:8008
    volumes:
      - /tmp:/tmp
    links:
      - config-server
      - rabbitmq
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq

  task-service:
    image: smarterbalanced/rdw-ingest-task-service
    ports:
      - 8084:8008
    volumes:
      - /tmp:/tmp
    links:
      - config-server
      - import-service
      - rabbitmq
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq

  migrate-reporting:
    image: smarterbalanced/rdw-ingest-migrate-reporting
    ports:
      - 8085:8008
    links:
      - config-server
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq
