sql:
  reporting:
    migrate:
      findLastMigratedAt: >-
        SELECT MAX(m.last_at) FROM migrate m WHERE m.status = 20

      create: >-
        INSERT INTO migrate (job_id, status, first_at, last_at, size, migrate_codes, migrate_embargo)
          VALUES (:job_id, :status, :first_at, :last_at, :size, :migrate_codes, :migrate_embargo)

      delete: >-
        DELETE FROM migrate WHERE id = :id

      updateStatusById: >-
        UPDATE migrate SET status = :status
          WHERE id = :id

      findLast: >-
        SELECT id, job_id, status, first_at, last_at, size, migrate_codes, migrate_embargo
          FROM migrate ORDER BY id DESC LIMIT 1

  warehouse:
    import:
      findAllImportStatus: >-
         SELECT name FROM import_status

      findImportState: >-
         SELECT start, stop, cnt FROM (

            (SELECT CASE WHEN :prev IS NULL
               THEN MIN(created)
                    ELSE :prev END AS start
             FROM import) s1,

            (SELECT
                MAX(updated) AS stop,
                count(*)     AS cnt
              FROM (SELECT updated
                    FROM import
                    WHERE status != 0 AND (:prev IS NULL OR updated > :prev) AND updated < CURRENT_TIMESTAMP(6)
                    ORDER BY updated
                    LIMIT :size) AS batch) s2
          )

      existsImportContentInTimeRange:
          SELECT 1 AS existsCodeImportContent
            FROM import
          WHERE content = :content
             AND ((status != 0 AND updated >= :first_at AND updated <= :last_at) OR
               (status = 0 AND created <= :last_at))
          LIMIT 1

  embargo:
    SELECT school_year, district_id, subject_id, individual, aggregate from district_embargo;
