sql:
  # AssessmentTypeRepository
  asmtType:
    findCodeById: >-
        SELECT code FROM asmt_type WHERE id= :id

  # EthnicityRepositoryImpl
  ethnicity:
    findIdByName: >-
        SELECT id FROM ethnicity WHERE name= :name

    findAllNames: >-
        SELECT name FROM ethnicity

  # GenderRepositoryImpl
  gender:
    findIdByName: >-
        SELECT id FROM gender WHERE name= :name

  # GenderRepositoryImpl
  subject:
    findIdByName: >-
        SELECT id FROM subject WHERE name= :name

  # GradeRepositoryImpl
  grade:
    findIdByCode: >-
        SELECT id FROM grade WHERE code= :code

 # AdminConditionRepositoryImpl
  administrationCondition:
    findIdByName: >-
        SELECT id FROM administration_condition WHERE name= :name

 # CompletenessnRepositoryImpl
  completeness:
    findIdByName: >-
        SELECT id FROM completeness WHERE name= :name

 # ItemTraitRepository
  itemTraitScore:
    findAll: >-
        SELECT * from item_trait_score

  # AssessmentRepository
  assessment:
    findOneByNaturalId: >-
        SELECT id, natural_id, grade_id,type_id, subject_id, school_year FROM asmt WHERE natural_id= :natural_id

    # this is a stubbed out method - TODO: to be deleted
    create: >-
        INSERT INTO asmt (natural_id, grade_id,type_id, subject_id, school_year, import_id) VALUES
                       (:natural_id, :grade_id, :type_id, :subject_id, :school_year, (select id from import limit 1))

    # this is a stubbed out method - TODO: to be deleted
    createItems: >-
        INSERT INTO item (claim_id, target_id, natural_id, asmt_id, dok_id, difficulty, max_points, math_practice, allow_calc) VALUES
          (null, null, :natural_id, :asmt_id, 1, 0.5, 5, null, null)

    subjectClaimScore:
      findBySubjectAndAsmtType: >-
        SELECT id, code FROM subject_claim_score WHERE subject_id = :subject_id and asmt_type_id =:asmt_type_id

    item:
      findAllForAssessment: >-
        SELECT id, natural_id from item where asmt_id = :asmt_id order by natural_id asc

  # ExamRepository
  exam:
    create: >-
       INSERT INTO exam (exam_student_id, school_year, import_id,  asmt_id, asmt_version, opportunity, status, completeness_id, administration_condition_id, session_id, scale_score, scale_score_std_err, achievement_level, completed_at) VALUES
                       (:exam_student_id, :school_year, :import_id, :asmt_id, :asmt_version, :opportunity, :status, :completeness_id, :administration_condition_id, :session_id, :scale_score, :scale_score_std_err, :achievement_level, :completed_at)
    examClaimScore:
      create: >-
        INSERT INTO exam_claim_score (exam_id, subject_claim_score_id, scale_score, scale_score_std_err, category) VALUES
                                    (:exam_id, :subject_claim_score_id, :scale_score, :scale_score_std_err, :category)
    examItem:
      create: >-
        INSERT INTO exam_item (exam_id, item_id, score, score_status, response, position,
                                  trait_evidence_elaboration_score, trait_evidence_elaboration_score_status,
                                  trait_organization_purpose_score, trait_organization_purpose_score_status,
                                  trait_conventions_score, trait_conventions_score_status) VALUES
                            (:exam_id, :item_id, :score, :score_status, :response, :position,
                                  :trait_evidence_elaboration_score, :trait_evidence_elaboration_score_status,
                                  :trait_organization_purpose_score, :trait_organization_purpose_score_status,
                                  :trait_conventions_score, :trait_conventions_score_status)
                           
    examStudent:
      create: >-
        INSERT INTO exam_student (grade_id, student_id, school_id, iep, lep, section504, economic_disadvantage, migrant_status, eng_prof_lvl, t3_program_type, language_code, prim_disability_type) VALUES
                              (:grade_id, :student_id, :school_id, :iep, :lep, :section504, :economic_disadvantage, :migrant_status, :eng_prof_lvl, :t3_program_type, :language_code, :prim_disability_type)

  # IabExamRepository
  iabExam:
    create: >-
      INSERT INTO iab_exam (iab_exam_student_id, school_year, import_id, asmt_id, asmt_version, opportunity, status, completeness_id, administration_condition_id, session_id, scale_score, scale_score_std_err, category, completed_at) VALUES
                           (:iab_exam_student_id, :school_year, :import_id, :asmt_id, :asmt_version, :opportunity, :status, :completeness_id, :administration_condition_id, :session_id, :scale_score, :scale_score_std_err, :category, :completed_at)

    iabExamItem:
      create: >-
        INSERT INTO iab_exam_item (iab_exam_id, item_id, score, score_status, response, position,
                                          trait_evidence_elaboration_score, trait_evidence_elaboration_score_status,
                                          trait_organization_purpose_score, trait_organization_purpose_score_status,
                                          trait_conventions_score, trait_conventions_score_status) VALUES
                                 (:iab_exam_id, :item_id, :score, :score_status, :response, :position,
                                          :trait_evidence_elaboration_score, :trait_evidence_elaboration_score_status,
                                          :trait_organization_purpose_score, :trait_organization_purpose_score_status,
                                          :trait_conventions_score, :trait_conventions_score_status)

    iabExamStudent:
      create: >-
        INSERT INTO iab_exam_student (grade_id, student_id, school_id, iep, lep, section504, economic_disadvantage, migrant_status, eng_prof_lvl, t3_program_type, language_code, prim_disability_type) VALUES
                                  (:grade_id, :student_id, :school_id, :iep, :lep, :section504, :economic_disadvantage, :migrant_status, :eng_prof_lvl, :t3_program_type, :language_code, :prim_disability_type)

  studentEthnicity:
    findAllIds:
      SELECT ethnicity_id from student_ethnicity where student_id = :student_id

    create: >-
        INSERT INTO student_ethnicity (student_id, ethnicity_id) VALUES (:student_id, :ethnicity_id)

    delete: >-
        DELETE FROM student_ethnicity where student_id = :student_id

  student:
    updateImportId:
        UPDATE student SET import_id = :import_id WHERE id = :student_id

  studentGroup:
    create: >-
      INSERT INTO student_group (name, school_id, school_year, subject_id, active, creator, created, import_id)
        VALUES (:name, :school_id, :school_year, :subject_id, :active, :creator, :created, :import_id)

    findIdByNameAndSchoolAndYear: >-
      SELECT id FROM student_group
        WHERE name=:name AND school_id=:school_id AND school_year=:school_year

    addStudentMembership: >-
      INSERT IGNORE INTO student_group_membership (student_group_id, student_id) VALUES (?, ?)