# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  security:
    enabled: false
server:
  port: 8008

spring:
  cache:
    type: SIMPLE
    cache-names: completeness, adminCondition, assessmentType, ethnicity, gender, grade, subject, school, accCode, schoolId

  cloud:
    stream:
      bindings:
        input:
          destination: EXAM
          group: default

  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false&useLegacyDatetimeCode=false&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 10
    initialSize: 4
    maxWait: 10000

jdbc:
  retry:
    default:
      max-attempts: 4
      delay: 30

sbac:
  scaleScore:
    min: 1500
    max: 3500
  itemScore:
    min: -1
    max: 20
