spring:
  cache:
    type: SIMPLE
    cache-names: completeness, adminCondition, assessmentType, ethnicity, gender, grade, subject, school

  cloud:
    stream:
      bindings:
        input:
          destination: exams-payload

  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false

