management:
  security:
    enabled: false

spring:
  cache:
    type: SIMPLE
    cache-names: completeness, adminCondition, assessmentType, ethnicity, gender, grade, subject, school

  cloud:
    stream:
      bindings:
        input:
          destination: exam-payload

  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false