sql:
  # JdbcAssessmentTypeRepository
  asmtType:
    findCodeById: >-
        SELECT code FROM asmt_type WHERE id= :id

  # JdbcEthnicityRepository
  ethnicity:
    findIdByCode: >-
        SELECT id FROM ethnicity WHERE code= :code

    findAllCodes: >-
        SELECT code FROM ethnicity

  # JdbcGenderRepository
  gender:
    findIdByCode: >-
        SELECT id FROM gender WHERE code= :code

  # JdbcGenderRepository
  subject:
    findIdByCode: >-
        SELECT id FROM subject WHERE code= :code

  # JdbcGradeRepository
  grade:
    findIdByCode: >-
        SELECT id FROM grade WHERE code= :code

  # JdbcAdminConditionRepository
  administrationCondition:
    findIdByCode: >-
        SELECT id FROM administration_condition WHERE code= :code

  # JdbcCompletenessRepository
  completeness:
    findIdByCode: >-
        SELECT id FROM completeness WHERE code= :code

  # ItemTraitRepository
  itemTraitScore:
    findAll: >-
        SELECT * from item_trait_score

  # JdbcAccommodationRepository
  accommodation:
    findIdByCode: >-
        SELECT id FROM accommodation WHERE code= :code

    findIdsByCodes: >-
        SELECT id FROM accommodation WHERE code in (:codes)

  # JdbcAssessmentRepository
  assessment:
    findOneByNaturalId: >-
        SELECT a.id, a.natural_id, g.code as grade_code, a.type_id, a.subject_id, s.code as subject_code
          FROM asmt a
            JOIN subject s ON s.id = a.subject_id
            JOIN grade g ON g.id = a.grade_id
          WHERE a.natural_id= :natural_id

    subjectClaimScore:
      findBySubjectAndAsmtType: >-
        SELECT id, code FROM subject_claim_score WHERE subject_id = :subject_id and asmt_type_id =:asmt_type_id

    item:
      findAllForAssessment: >-
        SELECT id, natural_id from item where asmt_id = :asmt_id order by natural_id asc

  # JdbcExamRepository
  exam:
    create: >-
      INSERT INTO exam (type_id, exam_student_id, school_year, import_id, update_import_id, asmt_id, asmt_version, opportunity, oppId, completeness_id, administration_condition_id, session_id, scale_score, scale_score_std_err, performance_level, completed_at) VALUES
                       (:type_id, :exam_student_id, :school_year, :import_id, :update_import_id, :asmt_id, :asmt_version, :opportunity, :oppId, :completeness_id, :administration_condition_id, :session_id, :scale_score, :scale_score_std_err, :performance_level, :completed_at)

    update: >-
      UPDATE exam
      SET
        type_id = :type_id,
        school_year = :school_year,
        update_import_id = :update_import_id,
        asmt_id = :asmt_id,
        asmt_version = :asmt_version,
        opportunity = :opportunity,
        oppId = :oppId,
        completeness_id = :completeness_id,
        administration_condition_id = :administration_condition_id,
        session_id = :session_id,
        scale_score = :scale_score,
        scale_score_std_err = :scale_score_std_err,
        performance_level = :performance_level,
        completed_at = :completed_at
      WHERE id = :id

    findOne: >-
      SELECT
        e.id,
        e.type_id,
        e.exam_student_id,
        e.school_year,
        e.asmt_id,
        e.asmt_version,
        e.opportunity,
        e.oppId,
        e.completeness_id,
        e.administration_condition_id,
        e.session_id,
        e.scale_score,
        e.scale_score_std_err,
        e.performance_level,
        e.completed_at,
        est.grade_id,
        est.student_id,
        est.school_id,
        est.iep,
        est.lep,
        est.section504,
        est.economic_disadvantage,
        est.migrant_status,
        est.eng_prof_lvl,
        est.t3_program_type,
        est.language_code,
        est.prim_disability_type
      FROM exam e
        JOIN exam_student est ON est.id = e.exam_student_id
      WHERE e.asmt_id = :asmt_id
        AND e.oppId = :opportunity_id
        AND est.student_id = :student_id

    examClaimScore:
      create: >-
        INSERT INTO exam_claim_score (exam_id, subject_claim_score_id, scale_score, scale_score_std_err, category) VALUES
                                    (:exam_id, :subject_claim_score_id, :scale_score, :scale_score_std_err, :category)

      update: >-
        UPDATE exam_claim_score
        SET
          subject_claim_score_id = :subject_claim_score_id,
          scale_score = :scale_score,
          scale_score_std_err = :scale_score_std_err,
          category = :category
        WHERE id = :id

      delete: >-
        DELETE FROM exam_claim_score
        WHERE id IN (:ids)

      findByExamId: >-
        SELECT
          id,
          subject_claim_score_id,
          scale_score,
          scale_score_std_err,
          category
        FROM exam_claim_score
        WHERE exam_id = :exam_id

    examItem:
      create: >-
        INSERT INTO exam_item (exam_id, item_id, score, score_status, response, position,
                                  trait_evidence_elaboration_score, trait_evidence_elaboration_score_status,
                                  trait_organization_purpose_score, trait_organization_purpose_score_status,
                                  trait_conventions_score, trait_conventions_score_status) VALUES
                            (:exam_id, :item_id, :score, :score_status, :response, :position,
                                  :trait_evidence_elaboration_score, :trait_evidence_elaboration_score_status,
                                  :trait_organization_purpose_score, :trait_organization_purpose_score_status,
                                  :trait_conventions_score, :trait_conventions_score_status)

      update: >-
        UPDATE exam_item
        SET
          score = :score,
          score_status = :score_status,
          response = :response,
          position = :position,
          trait_evidence_elaboration_score = :trait_evidence_elaboration_score,
          trait_evidence_elaboration_score_status = :trait_evidence_elaboration_score_status,
          trait_organization_purpose_score = :trait_organization_purpose_score,
          trait_organization_purpose_score_status = :trait_organization_purpose_score_status,
          trait_conventions_score = :trait_conventions_score,
          trait_conventions_score_status = :trait_conventions_score_status
        WHERE id = :id

      delete: >-
        DELETE FROM exam_item
        WHERE id IN (:ids)

      findByExamId: >-
        SELECT
          id,
          exam_id,
          item_id,
          score,
          score_status,
          response,
          position,
          trait_evidence_elaboration_score,
          trait_evidence_elaboration_score_status,
          trait_organization_purpose_score,
          trait_organization_purpose_score_status,
          trait_conventions_score,
          trait_conventions_score_status
        FROM exam_item
        WHERE exam_id = :exam_id

    examStudent:
      create: >-
        INSERT INTO exam_student (grade_id, student_id, school_id, iep, lep, section504, economic_disadvantage, migrant_status, eng_prof_lvl, t3_program_type, language_code, prim_disability_type) VALUES
                              (:grade_id, :student_id, :school_id, :iep, :lep, :section504, :economic_disadvantage, :migrant_status, :eng_prof_lvl, :t3_program_type, :language_code, :prim_disability_type)

      update: >-
        UPDATE exam_student
        SET
          grade_id = :grade_id,
          student_id = :student_id,
          school_id = :school_id,
          iep = :iep,
          lep = :lep,
          section504 = :section504,
          economic_disadvantage = :economic_disadvantage,
          migrant_status = :migrant_status,
          eng_prof_lvl = :eng_prof_lvl,
          t3_program_type = :t3_program_type,
          language_code = :language_code,
          prim_disability_type = :prim_disability_type
        WHERE id = :id

    accommodation:
      create: >-
        INSERT INTO exam_available_accommodation (exam_id, accommodation_id) VALUES (:exam_id, :accommodation_id)

      delete: >-
        DELETE FROM exam_available_accommodation
        WHERE exam_id = :exam_id
          AND accommodation_id IN (:accommodation_ids)

      findByExamId: >-
        SELECT accommodation_id
        FROM exam_available_accommodation
        WHERE exam_id = :exam_id

  school:
    findIdByNaturalId: >-
      SELECT id FROM school WHERE natural_id = :natural_id

  studentEthnicity:
    findAllIds:
      SELECT ethnicity_id from student_ethnicity where student_id = :student_id

    create: >-
        INSERT INTO student_ethnicity (student_id, ethnicity_id) VALUES (:student_id, :ethnicity_id)

    delete: >-
        DELETE FROM student_ethnicity where student_id = :student_id

  student:
    updateImportId:
        UPDATE student SET update_import_id = :update_import_id WHERE id = :student_id

  studentGroup:
    findIdByNameAndSchoolAndYear: >-
      SELECT id FROM student_group
        WHERE name=:name AND school_id=:school_id AND school_year=:school_year

    addStudentMembership: >-
      INSERT IGNORE INTO student_group_membership (student_group_id, student_id) VALUES (?, ?)

    updateImportId:
      UPDATE student_group SET update_import_id = ? WHERE id = ?

    existsStudentInGroup:
      SELECT (CASE WHEN EXISTS (SELECT 1 FROM student_group_membership WHERE student_group_id = :student_group_id and student_id = :student_id) THEN true ELSE false END) exist