# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  security:
    enabled: false
server:
  port: 8008
  tomcat:
    max-connections: 2
    max-threads: 2

spring:
  cache:
    type: SIMPLE
    cache-names: adminCondition, assessmentType, completeness, ethnicity, ethnicityCodes, gender, grade, subject, subjectClaimTargets, accCode, elas

  cloud:
    stream:
      bindings:
        input:
          destination: EXAM
          group: default

  datasource:
    url: "\
      jdbc:mysql://${spring.datasource.url-server:localhost:3306}/${spring.datasource.url-schema:warehouse}\
      ?useSSL=${spring.datasource.use-ssl:false}\
      &useLegacyDatetimeCode=${spring.datasource.use-legacy-datetime-code:false}\
      &characterEncoding=${spring.datasource.character-encoding:utf8}\
      &rewriteBatchedStatements=${spring.datasource.rewrite-batched-statements:true}\
      &noAccessToProcedureBodies=${spring.datasource.no-access-to-procedure-bodies:true}\
      &connectTimeout=${spring.datasource.connect-timeout:10000}\
      &socketTimeout=${spring.datasource.socket-timeout:40000}\
      "
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    validationQueryTimeout: 10000
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 12
    initialSize: 6
    maxWait: 10000
    jdbcInterceptors: "QueryTimeoutInterceptor(queryTimeout=30)"

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  profiles:
    include: ingest-common

jdbc:
  retry:
    default:
      max-attempts: 4
      delay: 30
      multiplier: 2

validation:
  examProcessor:
    requiredDataElements:
      - FirstName
      - LastOrSurname
      - Birthdate
      - Sex
      - EconomicDisadvantageStatus
      - IDEAIndicator