# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  security:
    enabled: false
server:
  port: 8008
  tomcat:
    max-connections: 2
    max-threads: 2

spring:
  cache:
    type: SIMPLE
    cache-names: completeness, adminCondition, assessmentType, ethnicity, ethnicityCodes, gender, grade, subject, accCode

  cloud:
    stream:
      bindings:
        input:
          destination: EXAM
          group: default

  datasource:
    url-server: localhost:3306
    url-schema: warehouse
    url: jdbc:mysql://${spring.datasource.url-server}/${spring.datasource.url-schema}?useSSL=false&useLegacyDatetimeCode=false&characterEncoding=utf8&rewriteBatchedStatements=true&noAccessToProcedureBodies=true
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 12
    initialSize: 6
    maxWait: 10000

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

jdbc:
  retry:
    default:
      max-attempts: 4
      delay: 30

sbac:
  scaleScore:
    min: 1500
    max: 3500
  itemScore:
    min: -1
    max: 20
