# docker-compose specs for rdw ingest processes
#
# Before running this spec, set the DATAWAREHOUSE_HOST; if that is the (mac) docker host:
# $ export DATAWAREHOUSE_HOST=$(ipconfig getifaddr en0)
# This value must be reset whenever you change networks.

version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  exam-service:
    image: fwsbac/rdw-ingest-exam-service
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.datasource.url=jdbc:mysql://dwhost:3306/warehouse?useSSL=false
    extra_hosts:
      - "dwhost:$DATAWAREHOUSE_HOST"

  exam-processor:
    image: fwsbac/rdw-ingest-exam-processor
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.datasource.url=jdbc:mysql://dwhost:3306/warehouse?useSSL=false
    extra_hosts:
      - "dwhost:$DATAWAREHOUSE_HOST"