spring:

  batch_datasource:
    url: jdbc:mysql://localhost:3306/spring_batch_reporting?useSSL=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false

  warehouse_datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false

  reporting_datasource:
    url: jdbc:mysql://localhost:3306/reporting?useSSL=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false