sql:
  reporting:
    findMigrateLastImportId: >-
      SELECT MAX(m.last_import_id)
        FROM `reporting-test`.migrate m
        WHERE m.status > 0

  warehouse:
    findMaxExamImportId: >-
      SELECT MAX(i.id)
        FROM `warehouse-test`.import i
          JOIN `warehouse-test`.import_content ic ON i.content = ic.id
        WHERE ic.name = 'EXAM'