sql:
  reporting:
    findMigrateLastImportId: >-
      SELECT MAX(reporting.migrate.last_import_id)
        FROM reporting.migrate
        WHERE reporting.migrate.status > 0

  warehouse:
    findMaxExamImportId: >-
      SELECT MAX(import.id)
        FROM import
          JOIN import_content ON import.content = import_content.id
        WHERE import_content.name = 'EXAM'