sql:
  reporting:
    migrate:
      findLastMigratedImportId: >-
        SELECT MAX(m.last_import_id) FROM reporting.migrate m WHERE m.status = 20

      create: >-
        INSERT INTO reporting.migrate (job_id, status, first_import_id, last_import_id)
          VALUES (:job_id, :status, :first_import_id, :last_import_id)

      delete: >-
        DELETE FROM reporting.migrate WHERE id = :id

      updateStatusById: >-
        UPDATE reporting.migrate SET status = :status
          WHERE id = :id

      lastStatus: >-
        SELECT status FROM reporting.migrate ORDER BY id DESC LIMIT 1

  warehouse:
    import:
      findAllImportStatus: >-
        SELECT name FROM warehouse.import_status

      findImportState: >-
        SELECT start, stop, blocker FROM (
          (SELECT MIN(id) AS blocker FROM warehouse.import WHERE status = 0 AND id <= if(:prev IS NULL, :size, (:prev + :size))) s1,
          (SELECT MIN(id) AS start FROM warehouse.import WHERE (:prev IS NULL OR id > :prev) AND status = 1) s2,
          (SELECT MAX(id) AS stop FROM warehouse.import WHERE (:prev IS NULL OR id > :prev) AND id <= if(:prev IS NULL, :size, (:prev + :size)) AND status = 1) s3
        )