sql:
  reporting:
    migrate:
      findLastMigratedImportId:  >-
        SELECT MAX(m.last_import_id) FROM reporting.migrate m WHERE m.status = 20

      create:
        INSERT INTO reporting.migrate (id, status, first_import_id, last_import_id)
          VALUES (:id, :status, :first_import_id, :last_import_id);

      updateStatusById:
         UPDATE reporting.migrate
             SET status = :status
        WHERE id = :id

  warehouse:
    import:
      findMaxImportId:  >-
          SELECT MAX(i.id) FROM warehouse.import i WHERE i.status >= 0

      findMinImportId:  >-
          SELECT MIN(i.id) FROM warehouse.import i WHERE i.status >= 0

