sql:
  stage:
    entities:
        # ------------ import  --------------------------------------------------------------------
        import:
          sql:
            findMaxImportId:  >-
              SELECT MAX(i.id)
                FROM warehouse.import i
              WHERE i.status >= 0
            findMinImportId:  >-
              SELECT MIN(i.id)
                FROM warehouse.import i
              WHERE i.status >= 0
            findLastMigratedImportId:  >-
              SELECT MAX(m.last_import_id)
                FROM reporting.migrate m
              WHERE m.status = 20


  # ------------ original format ------------------------------------------------------------------
  # todo: refactor names
  warehouseToStage:
    findMaxExamImportId: >-
      SELECT MAX(i.id)
        FROM warehouse.import i
          JOIN warehouse.import_content ic ON i.content = ic.id
        WHERE ic.name = 'EXAM'
    findWarehouseSubjects: >-
      SELECT ws.id, ws.name FROM warehouse.subject ws ORDER BY ws.id ASC
    findReportingSubjects: >-
      SELECT rs.id, rs.name FROM reporting.subject rs ORDER BY rs.id ASC
    findWarehouseAsmtTypes: >-
      SELECT wat.id, wat.code, wat.name FROM warehouse.asmt_type wat ORDER BY wat.id ASC
    findReportingAsmtTypes: >-
      SELECT rat.id, rat.code, rat.name FROM reporting.asmt_type rat ORDER by rat.id ASC
    findWarehouseSubjectClaimScores: >-
      SELECT wscs.id, wscs.subject_id, wscs.asmt_type_id, wscs.code, wscs.name
        FROM warehouse.subject_claim_score wscs ORDER BY wscs.id ASC
    findReportingSubjectClaimScores: >-
      SELECT rscs.id, rscs.subject_id, rscs.asmt_type_id, rscs.code, rscs.name
        FROM reporting.subject_claim_score rscs ORDER BY rscs.id ASC
