sql:
  reporting:
    migrate:
      findLastMigratedImportId: >-
        SELECT MAX(m.last_import_id) FROM reporting.migrate m WHERE m.status = 20

      create: >-
        INSERT INTO reporting.migrate (job_id, status, first_import_id, last_import_id)
          VALUES (:job_id, :status, :first_import_id, :last_import_id)

      delete: >-
        DELETE FROM reporting.migrate WHERE id = :id

      updateStatusById: >-
        UPDATE reporting.migrate SET status = :status
          WHERE id = :id

      lastStatus: >-
        SELECT status FROM reporting.migrate ORDER BY id DESC LIMIT 1

  warehouse:
    import:
      findMinImportId: >-
        SELECT MIN(i.id) FROM warehouse.import i WHERE i.status >= 0

      findMaxImportIdNotMigrated: >-
        SELECT max(available.id) id
        FROM
          (SELECT id
           FROM warehouse.import
           WHERE id > :last_import_id
            AND status = 1
           ORDER BY id ASC
           LIMIT :batch_size
          ) AS available;


