sql:
  reporting:
    migrate:
      findLastMigratedAt: >-
        SELECT MAX(m.last_at) FROM reporting.migrate m WHERE m.status = 20

      create: >-
        INSERT INTO reporting.migrate (job_id, status, first_at, last_at)
          VALUES (:job_id, :status, :first_at, :last_at)

      delete: >-
        DELETE FROM reporting.migrate WHERE id = :id

      updateStatusById: >-
        UPDATE reporting.migrate SET status = :status
          WHERE id = :id

      lastStatus: >-
        SELECT status FROM reporting.migrate ORDER BY id DESC LIMIT 1

  warehouse:
    import:
      findAllImportStatus: >-
         SELECT name FROM warehouse.import_status

      findImportState: >-
         SELECT start, stop, cnt FROM (

            (SELECT CASE WHEN :prev IS NULL
               THEN MIN(created)
                    ELSE :prev END AS start
             FROM warehouse.import) s1,

            (SELECT
                MAX(updated) AS stop,
                count(*)     AS cnt
              FROM (SELECT updated
                    FROM warehouse.import
                    WHERE status != 0 AND (:prev IS NULL OR updated >= :prev) AND updated < CURRENT_TIMESTAMP(6)
                    ORDER BY updated
                    LIMIT :size) AS batch) s2
          )

      existsCodeImportContentInTimeRange:
          SELECT 1 AS existsCodeImportContent
            FROM warehouse.import wi
          WHERE wi.content = 3
             AND ((wi.status != 0 AND wi.updated >= :first_at AND wi.updated <= :last_at) OR
               (wi.status = 0 AND wi.created <= :last_at))
          LIMIT 1
