# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  security:
    enabled: false
server:
  port: 8008
  tomcat:
    max-connections: 2
    max-threads: 2

# A batch size of 2000 offers good performance with reasonable resource utilization (-Xmx512m). A larger batch
# size (e.g. 4000) may improve overall performance but the resource limits need to be raised (e.g. -Xmx768m).
migrate:
  batch:
    size: 2000
    delay: 60000

spring:
  reporting_datasource:
    url: "\
      jdbc:mysql://${spring.reporting_datasource.url-server:localhost:3306}/${spring.reporting_datasource.url-schema:reporting}\
      ?useSSL=${spring.reporting_datasource.use-ssl:false}\
      &useLegacyDatetimeCode=${spring.reporting_datasource.use-legacy-datetime-code:false}\
      &characterEncoding=${spring.reporting_datasource.character-encoding:utf8}\
      &rewriteBatchedStatements=${spring.reporting_datasource.rewrite-batched-statements:true}\
      "
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 10
    initialSize: 4

  warehouse_datasource:
    url: "\
      jdbc:mysql://${spring.warehouse_datasource.url-server:localhost:3306}/${spring.warehouse_datasource.url-schema:warehouse}\
      ?useSSL=${spring.warehouse_datasource.use-ssl:false}\
      &useLegacyDatetimeCode=${spring.warehouse_datasource.use-legacy-datetime-code:false}\
      &characterEncoding=${spring.warehouse_datasource.character-encoding:utf8}\
      "
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 10
    initialSize: 4

  batch:
    job:
      enabled: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    org.springframework.transaction: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.datasource.DataSourceTransactionManager: INFO