migrate:
  batch:
    size: 1000
    delay: 50000
    initialDelay: -1

spring:
  batch_datasource:
    url: jdbc:mysql://localhost:3306/spring_batch_reporting?useSSL=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false

  warehouse_datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false

  batch:
    job:
      enabled: false

logging:
  level:
    org.springframework.transaction: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.datasource.DataSourceTransactionManager: INFO