sql:
  reporting:
    findMigrateLastImportId: >-
      SELECT MAX(m.last_import_id)
        FROM ${rdw.sql.reporting}.migrate m
        WHERE m.status > 0

  warehouse:
    findMaxExamImportId: >-
      SELECT MAX(i.id)
        FROM ${rdw.sql.warehouse}.import i
          JOIN ${rdw.sql.warehouse}.import_content ic ON i.content = ic.id
        WHERE ic.name = 'EXAM'