# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  security:
    enabled: false
server:
  port: 8008

migrate:
  batch:
    size: 4000
    delay: 60000

spring:
  batch_datasource:
    url: jdbc:mysql://localhost:3306/spring_batch_reporting?useSSL=false&useLegacyDatetimeCode=false&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 10
    initialSize: 4

  warehouse_datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false&useLegacyDatetimeCode=false&characterEncoding=utf8
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 10
    initialSize: 4

  batch:
    job:
      enabled: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    org.springframework.transaction: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.datasource.DataSourceTransactionManager: INFO