management:
  security:
    enabled: false

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: MIGRATE
          group: default

  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false