sql:
  # AccommodationRepository
  accommodation:
    findIdByCode: >-
      SELECT id FROM accommodation WHERE code= :code

    create: >-
      INSERT INTO accommodation (code) VALUES (:code)

  # LanguageRepository
  language:
    findIdByCode: >-
      SELECT id FROM language WHERE code= :code

  # AccommodationTranslationRepository
  accommodationTranslation:
    create: >-
      INSERT INTO accommodation_translation (accId, langId, label)
         select (select id as accId from accommodation where code = :accCode), (select id as langId from language where code=:langCode), :label

    findByAccCodeAndLangCode: >-
      SELECT id FROM accommodation_translation WHERE accommodation_id=:accId AND language_id=:langId

    updateTranslation: >-
      UPDATE accommodation_translation SET label=:label WHERE accommodation_id=:accId AND language_id=:langId