sql:
  # AccommodationRepository
  accommodation:
    findIdByCode: >-
      SELECT id FROM accommodation WHERE code= :code

  # LanguageRepository
  language:
    findIdByName: >-
      SELECT id FROM language WHERE code= :code

  # AccommodationTranslationRepository
  accommodationTranslation:
    create: >-
      INSERT INTO accommodation_translation (accId, langId, label)
         select (select id as accId from accommodation where code = :accCode), (select id as langId from language where code=:langCode), :label

