sql:
  import:
    exams: >-
      SELECT s.ssid, a.natural_id, e.school_year, e.oppId, i.batch, i.id
      FROM (
             SELECT
               i.batch,
               i.id
             FROM import i
             WHERE i.content = 1
                   AND (:batch IS NULL OR i.batch = :batch)
                   AND (:creator IS NULL OR i.creator = :creator)
                   AND (:before IS NULL OR i.created < :before)
                   AND (:after IS NULL OR i.updated > :after)
             ORDER BY i.updated, i.id
        ) AS i
        JOIN exam e ON e.import_id = i.id
        JOIN student s ON s.id = e.student_id
        JOIN asmt a ON a.id = e.asmt_id;

    exists: >-
      SELECT EXISTS(
        SELECT 1 FROM import i
        WHERE i.content = 1
          AND (:batch IS NULL OR i.batch = :batch)
          AND (:creator IS NULL OR i.creator = :creator)
          AND (:before IS NULL OR i.created < :before)
          AND (:after IS NULL OR i.updated > :after)
        LIMIT 1)

    status: >-
      SELECT s.ssid, a.natural_id, e.school_year, e.oppId, i.batch, i.id
        FROM import i
          JOIN exam e ON e.import_id = i.id
          JOIN student s ON s.id = e.student_id
          JOIN asmt a ON a.id = e.asmt_id
        WHERE i.content = 1
        LIMIT 1