server:
  port: 8761

spring:
  mail:
    host: email-smtp.us-west-2.amazonaws.com
    port: 465
    protocol: smtps
    username:
    password:

repository:
  import:
    host: http://localhost:8080
    auth:
      token:
      username: dwtest@example.com
      password: password


task:
  sendReconciliationReport:
    email:
      to: bsavage@fairwaytech.com
      from: bsavage@fairwaytech.com
      subject: Daily Reconciliation Report
      message: Please see attached CSV file for the daily imported exams.
