server:
  port: 8761

eureka:
  client:
    healthCheck:
      enabled: true
    lease:
      duration: 5
    register-with-eureka: false
    fetch-registry: true

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
