sql:
  import:
    exams: >-
      SELECT s.ssid, a.natural_id, e.school_year, e.oppId, i.batch, i.id
      FROM import i
        JOIN exam e ON e.import_id = i.id
        JOIN exam_student es ON es.id = e.exam_student_id
        JOIN student s ON s.id = es.student_id
        JOIN asmt a ON a.id = e.asmt_id
      WHERE i.content = 1 AND i.replay_id IS NULL
        AND (:batch IS NULL OR i.batch = :batch)
        AND (:creator IS NULL OR i.creator = :creator)
        AND (:before IS NULL OR i.created < :before)
        AND (:after IS NULL OR i.created > :after)
      ORDER BY i.id

    count: >-
      SELECT count(*) FROM import i
      WHERE i.content = 1 AND i.replay_id IS NULL
        AND (:batch IS NULL OR i.batch = :batch)
        AND (:creator IS NULL OR i.creator = :creator)
        AND (:before IS NULL OR i.created < :before)
        AND (:after IS NULL OR i.created > :after)

    status: >-
      SELECT s.ssid, a.natural_id, e.school_year, e.oppId, i.batch, i.id
        FROM import i
          JOIN exam e ON e.import_id = i.id
          JOIN exam_student es ON es.id = e.exam_student_id
          JOIN student s ON s.id = es.student_id
          JOIN asmt a ON a.id = e.asmt_id
        LIMIT 1