# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  security:
    enabled: false
server:
  port: 8008
  tomcat:
    max-connections: 2
    max-threads: 2

# spring auto-configured aws defense
cloud:
  aws:
    # there must be a default region when running locally
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false
    credentials:
      instance-profile: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false&characterEncoding=utf8&useLegacyDatetimeCode=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 10
    initialSize: 4

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

task:
# by default, all tasks are disabled for local dev environment; uncomment and set secrets/hosts to test
#  send-reconciliation-report:
#    cron: 0 0 14 * * *
#    query: status=PROCESSED&after=-PT24H
#    senders:
#      - type: ftp
#        server:
#        username:
#        password:
#      - type: log
#      - type: archive
#        root: file:///tmp/
#      - type: archive
#        root: s3:///bucket
#        cloud:
#          aws:
#            credentials:
#              access-key: AccessKey
#              secret-key: SecretKey
#            region:
#              static: us-west-2
#  update-organizations:
#    cron: 0 0 4 * * *
#    state: CA
#    art-client:
#      districts-url: https://art-deployment.sbtds.org/rest/district?stateAbbreviation={state}&pageSize=5000
#      groups-of-schools-url: https://art-deployment.sbtds.org/rest/groupofinstitution?stateAbbreviation={state}&pageSize=1000
#      schools-url: https://art-deployment.sbtds.org/rest/institution?stateAbbreviation={state}&pageSize=20000
#      status-url: https://art-deployment.sbtds.org/rest/status
#      oauth2:
#        access-token-uri: https://sso-deployment.sbtds.org:443/auth/oauth2/access_token?realm=/sbac
#        client-id: sbacdw
#        client-secret:
#        username: ca.admin@example.com
#        password:
#    import-service-client:
#      organizations-imports-url: http://localhost:8080/organizations/imports
#      status-url: http://localhost:8081/status
#      stub-auth: sbac;dwtest@example.com;|SBAC|ASMTDATALOAD|CLIENT|SBAC||||||||||||||
#  resubmit-unprocessed-imports:
#    cron: 0 0 13 * * *
#    import-service-client:
#      exams-imports-url: http://localhost:8080/exams/imports/resubmit
#      status-url: http://localhost:8081/status
#      stub-auth: sbac;dwtest@example.com;|SBAC|ASMTDATALOAD|CLIENT|SBAC||||||||||||||
#      oauth2:
#        access-token-uri: https://sso-deployment.sbtds.org:443/auth/oauth2/access_token?realm=/sbac
#        client-id: sbacdw
#        client-secret:
#        username: dwtest@example.com
#        password: