# do NOT leave this in; it is only disabled to aid in debugging
# either actuator end-points need to be served up on another port that is not exposed outside network
# or we need to enable security and create an internal user that has the ACTUATOR role
management:
  security:
    enabled: false

spring:
  mail:
    host: local
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false
    username: root
    password:
    testWhileIdle: true
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

task:
  send-reconciliation-report:
    cron: 0 0 14 * * *
    query: status=PROCESSED&after=-PT24H
    email:
      to: fairway.sbac.rdw.dev@gmail.com
      from: fairway.sbac.rdw.dev@gmail.com
      subject: Daily Reconciliation Report
      message: Please see attached CSV file for the daily imported exams.
  # by default, this task is disabled for local dev environment; uncomment and set secrets/hosts to test
#  update-organizations:
#    cron: 0 0 4 * * *
#    state: CA
#    art-client:
#      districts-url: https://art-deployment.sbtds.org/rest/district?stateAbbreviation={state}
#      groups-of-schools-url: https://art-deployment.sbtds.org/rest/groupofinstitution?stateAbbreviation={state}&pageSize=1000
#      schools-url: https://art-deployment.sbtds.org/rest/institution?stateAbbreviation={state}&pageSize=20000
#      status-url: https://art-deployment.sbtds.org/rest/status
#      oauth2:
#        access-token-uri: https://sso-deployment.sbtds.org:443/auth/oauth2/access_token?realm=/sbac
#        client-id: sbacdw
#        client-secret:
#        username: ca.admin@example.com
#        password:
#    import-service-client:
#      organizations-imports-url: http://localhost:8080/organizations/imports
#      status-url: http://localhost:8080/status
#      stub-auth: sbac;dwtest@example.com;|SBAC|ASMTDATALOAD|CLIENT|SBAC||||||||||||||
