# do NOT leave this in; it is only disabled to aid in debugging
# either actuator end-points need to be served up on another port that is not exposed outside network
# or we need to enable security and create an internal user that has the ACTUATOR role
management:
  security:
    enabled: false

# there needs to be a default aws region configured
cloud:
  aws:
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false
    credentials:
      instance-profile: false

# cause StubTokenServices to be used
security:
  oauth2:
    token-info-url: local

spring:
  # Force the (rabbit) queues to be created when posting messages so, even if
  # there are no consumers running, the messages will not get lost. Routing is
  # dynamic based on content but there is no way to do that here so we must
  # explicitly declare all possible output channels here (EXAM, PACKAGE, etc.).
  # The group names must be coordinated with the consumer application configs.
  cloud:
    stream:
      bindings:
        EXAM:
          producer:
            requiredGroups: default
        PACKAGE:
          producer:
            requiredGroups: default

  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 20
    initialSize: 4
    maxWait: 10000

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false