sql:
  import:
    count: >-
      SELECT count(*) from import

    create: >-
      INSERT INTO import (status, content, contentType, digest, batch, creator, created, message)
        VALUES (:status, :content, :contentType, :digest, :batch, :creator, :created, :message)

    delete: >-
      DELETE FROM import WHERE id=:id

    exists: >-
      SELECT (CASE WHEN EXISTS (SELECT 1 FROM import WHERE id=:id) THEN true ELSE false END) exist

    findBy: >-
      SELECT * FROM import WHERE (:content IS NULL OR content=:content)
          AND (:status IS NULL OR status = :status)
          AND (:batch IS NULL OR batch = :batch)
          AND (:creator IS NULL OR creator = :creator)
          AND (:before IS NULL OR created < :before)
          AND (:after IS NULL OR created > :after)

    findOne: >-
      SELECT * FROM import WHERE id=:id

    findOneByDigest: >-
      SELECT * FROM import WHERE digest=:digest

  importStatus:
    findAll: >-
      SELECT * FROM import_status