sql:
  import:
    count: >-
      SELECT count(*) from import

    create: >-
      INSERT INTO import (status, content, contentType, digest, batch, creator, message)
        VALUES (:status, :content, :contentType, :digest, :batch, :creator, :message)

    delete: >-
      DELETE FROM import WHERE id=:id

    exists: >-
      SELECT (CASE WHEN EXISTS (SELECT 1 FROM import WHERE id=:id) THEN true ELSE false END) exist

    findOne: >-
      SELECT * FROM import WHERE id=:id

    findOneByDigest: >-
      SELECT * FROM import WHERE digest=:digest

    findBy: >-
      SELECT *
      FROM import i
      WHERE (:content IS NULL OR i.content=:content)
        AND (:status IS NULL OR i.status = :status)
        AND (:batch IS NULL OR i.batch = :batch)
        AND (:creator IS NULL OR i.creator = :creator)
        AND (:before IS NULL OR i.created < :before)
        AND (:after IS NULL OR i.created > :after)
      ORDER BY i.id
      LIMIT :limit

  importStatus:
    findAll: >-
      SELECT * FROM import_status