# this application' security configurer doesn't play nice with the management web security auto configuration
# so disable that and, like the other apps, switch the actuator end-points to a less standard port
# (note that the server.port should still be set to the default 8080)
management:
  port: 8008
  security:
    enabled: false

# there needs to be a default aws region configured
cloud:
  aws:
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false
    credentials:
      instance-profile: false

# cause StubTokenServices to be used
security:
  oauth2:
    token-info-url: local

server:
  tomcat:
    max-connections: 96
    max-threads: 32

spring:
  # Force the (rabbit) queues to be created when posting messages so, even if
  # there are no consumers running, the messages will not get lost. Routing is
  # dynamic based on content but there is no way to do that here so we must
  # explicitly declare all possible output channels here (EXAM, PACKAGE, etc.).
  # The group names must be coordinated with the consumer application configs.
  cloud:
    stream:
      bindings:
        CODES:
          producer:
            requiredGroups: default
        EXAM:
          producer:
            requiredGroups: default
        ORGANIZATION:
          producer:
            requiredGroups: default
        PACKAGE:
          producer:
            requiredGroups: default

  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false&useLegacyDatetimeCode=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 20
    initialSize: 4
    maxWait: 10000

  http:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false