# do NOT leave this in; it is only disabled to aid in debugging
# either actuator end-points need to be served up on another port that is not exposed outside network
# or we need to enable security and create an internal user that has the ACTUATOR role
management:
  security:
    enabled: false

# there needs to be a default aws region configured
cloud:
  aws:
    region:
      auto: false
      static: us-west-2
    stack:
      auto: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  ldap:
    embedded:
      base-dn: dc=smarterbalanced,dc=org
      ldif: classpath:user.ldif
      validation:
        enabled: false
