sql:
  # JdbcGradeRepository
  grade:
    findIdByCode: >-
      SELECT id FROM grade WHERE code = :code

  # JdbcLanguageRepository
  language:
    findIdByCode: >-
      SELECT id FROM language WHERE (code = LOWER(:code) OR altcode = :code)

  # JdbcImportRepository
  import:
    updateStatusById: >-
      UPDATE import SET status = :status WHERE id = :id

    updateStatusAndMessageById: >-
      UPDATE import SET status = :status, message = :message WHERE id = :id
