DELETE FROM school_year WHERE year IN (1999,1998);
DELETE FROM completeness WHERE id IN (-99,-98);
DELETE FROM administration_condition WHERE id IN (-99,-98, -97, -96);
DELETE FROM ethnicity WHERE id IN (-99,-98);
DELETE FROM gender WHERE id IN (-99,-98);
DELETE FROM accommodation_translation WHERE accommodation_id IN (-99, -98);
DELETE FROM accommodation WHERE id IN (-99,-98);
DELETE FROM school_year WHERE year IN (1999,1998);
DELETE FROM depth_of_knowledge  WHERE id IN (-99,-98);
DELETE FROM math_practice  WHERE practice IN (-99,-98);
DELETE FROM item_trait_score WHERE id IN (-99,-98);
DELETE FROM target WHERE id IN (-99,-98);
DELETE FROM common_core_standard WHERE id IN (-99,-98);
DELETE FROM item_difficulty_cuts  WHERE id IN (-99,-98);
DELETE FROM claim WHERE id IN (-99,-98);
DELETE FROM grade WHERE id IN (-99,-98);
