oauth2:
  access-token-uri: https://sso-deployment.sbtds.org:443/auth/oauth2/access_token?realm=/sbac
  client-id: sbacdw
  client-secret: sbacdw123
  token-info-uri: https://sso-deployment.sbtds.org:443/auth/oauth2/tokeninfo
  cache:
    size: 10
    expire: 15

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: exams-payload

  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false