# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
# spring auto-configured aws defense
# use LocalArchiveService by default
archive:
  root: ${rdw.resource.root:}
  cloud:
    aws:
      # rdw-ingest
      credentials:
        accessKey: ${rdw.aws.access.key:}
        secretKey: ${rdw.aws.secret.key:}
      region:
        auto: false
        static: us-west-2

cloud:
  aws:
    # there must be a default region when running locally
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false
    credentials:
      instance-profile: false

management:
  security:
    enabled: false
server:
  port: 8008
  tomcat:
    max-connections: 2
    max-threads: 2

migrate:
  aws:
    location: MigrateOlap
    redshift:
      role: ${rdw.migrate.aws.redshift.role}

  batch:
    size: 100000
    delay: 60000

spring:
  batch:
    job:
      enabled: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  migrate_datasource:
    url: "\
      jdbc:mysql://${spring.migrate_datasource.url-server:localhost:3306}/${spring.migrate_datasource.url-schema:migrate_olap}\
      ?useSSL=${spring.migrate_datasource.use-ssl:false}\
      &useLegacyDatetimeCode=${spring.migrate_datasource.use-legacy-datetime-code:false}\
      &characterEncoding=${spring.migrate_datasource.character-encoding:utf8}\
      "
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 10
    initialSize: 4

  reporting_datasource:
    url: "\
      jdbc:redshift://${spring.spring.reporting_datasource.url-server:localhost:3306?${spring.spring.reporting_datasource.url-schema:reporting_olap}
      "
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.amazon.redshift.jdbc42.Driver

  warehouse_datasource:
    url: "\
      jdbc:mysql://${spring.warehouse_datasource.url-server:localhost:3306}/${spring.warehouse_datasource.url-schema:warehouse}\
      ?useSSL=${spring.warehouse_datasource.use-ssl:false}\
      &useLegacyDatetimeCode=${spring.warehouse_datasource.use-legacy-datetime-code:false}\
      &characterEncoding=${spring.warehouse_datasource.character-encoding:utf8}\
      "
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 10
    initialSize: 4

logging:
  level:
    org.springframework.transaction: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.datasource.DataSourceTransactionManager: INFO