sql:
  migrate:
    entities:
        # ------------ administration_condition  -------------------------------------------------------------------
        administration_condition:
          sql:
            update:  >-
               UPDATE administration_condition
               SET
                 code = sac.code
               FROM
                  staging_administration_condition sac where sac.id = administration_condition.id;

            insert: >-
                INSERT INTO administration_condition (id, code)
                  SELECT
                    sac.id,
                    sac.code
                  FROM staging_administration_condition sac
                    LEFT JOIN administration_condition rac ON rac.id = sac.id
                  WHERE rac.id IS NULL;

            delete: >-
               DELETE FROM administration_condition
               WHERE NOT EXISTS(SELECT sac.id FROM staging_administration_condition sac WHERE sac.id = administration_condition.id);

        # ------------ completeness  -------------------------------------------------------------------
        completeness:
          sql:
            update:  >-
               UPDATE completeness
               SET
                 code = sc.code
               FROM
                  staging_completeness sc where sc.id = completeness.id;

            insert: >-
                INSERT INTO completeness (id, code)
                  SELECT
                    sc.id,
                    sc.code
                  FROM staging_completeness sc
                    LEFT JOIN completeness rc ON rc.id = sc.id
                  WHERE rc.id IS NULL;

            delete: >-
               DELETE FROM completeness
               WHERE NOT EXISTS(SELECT sc.id FROM staging_completeness sc WHERE sc.id = completeness.id);

       # ------------ Ethnicity ------------------------------------------------------------------------
        ethnicity:
          sql:
            update:  >-
               UPDATE ethnicity
               SET
                 code = se.code
               FROM
                  staging_ethnicity se where ethnicity.id = se.id;

            insert: >-
                INSERT INTO ethnicity (id, code)
                  SELECT
                    se.id,
                    se.code
                  FROM staging_ethnicity se
                    LEFT JOIN ethnicity re ON se.id = re.id
                  WHERE re.id IS NULL;

            delete: >-
               DELETE FROM ethnicity
               WHERE NOT EXISTS(SELECT se.id FROM staging_ethnicity se WHERE ethnicity.id = se.id);

        # ------------ gender  -------------------------------------------------------------------
        gender:
          sql:
            update:  >-
               UPDATE gender
               SET
                 code = sg.code
               FROM
                  staging_gender sg where sg.id = gender.id;

            insert: >-
                INSERT INTO gender (id, code)
                  SELECT
                    sg.id,
                    sg.code
                  FROM staging_gender sg
                    LEFT JOIN gender rg ON rg.id = sg.id
                  WHERE rg.id IS NULL;
            delete: >-
               DELETE FROM gender
               WHERE NOT EXISTS(SELECT sg.id FROM staging_gender sg WHERE sg.id = gender.id);

        # ------------ grade  -------------------------------------------------------------------
        grade:
          sql:
            update:  >-
               UPDATE grade
               SET
                 code = sg.code,
                 name = sg.name
               FROM
                  staging_grade sg where sg.id = grade.id;

            insert: >-
                INSERT INTO grade (id, code, name)
                  SELECT
                    sg.id,
                    sg.code,
                    sg.name
                  FROM staging_grade sg
                    LEFT JOIN gender rg ON rg.id = sg.id
                  WHERE rg.id IS NULL;
            delete: >-
               DELETE FROM grade
               WHERE NOT EXISTS(SELECT sg.id FROM staging_grade sg WHERE sg.id = grade.id);

      # ------------ student -----------------------------------------------------------------------
        student:
          sql:
            insert: >-
              INSERT INTO student (id,  gender_id, migrate_id)
                SELECT DISTINCT
                  ss.id,
                  rg.id,
                  ss.migrate_id
                FROM staging_student ss
                  LEFT JOIN student rs ON rs.id = ss.id
                  LEFT JOIN gender rg ON ss.gender_id = rg.id
                WHERE rs.id IS NULL and ss.deleted = 0;

            update: >-
              UPDATE student
              SET
                gender_id  = ss.gender_id,
                migrate_id = ss.migrate_id
              FROM staging_student ss
                JOIN gender rg ON ss.gender_id = rg.id
              WHERE ss.id = student.id;

            delete: >-
              DELETE FROM student
                USING staging_student ss
              WHERE ss.id = student.id AND ss.deleted = 1;

      # ------------ student_ethnicity -----------------------------------------------------------------------
        student_ethnicity:
          sql:
            insert: >-
               INSERT INTO student_ethnicity (student_id, ethnicity_id)
                 SELECT
                   sue.student_id,
                   sue.ethnicity_id
                 FROM staging_student_ethnicity sue
                   LEFT JOIN student_ethnicity rse
                     ON (rse.student_id = sue.student_id AND rse.ethnicity_id = sue.ethnicity_id)
                   JOIN ethnicity re on re.id = sue.ethnicity_id
                 WHERE rse.student_id IS NULL;

            deleteAsPartOfParentUpdate: >-
               DELETE FROM student_ethnicity
                 USING staging_student ss
               WHERE ss.id = student_ethnicity.student_id AND ss.deleted = 0
                     AND NOT EXISTS(SELECT sse.student_id FROM staging_student_ethnicity sse WHERE sse.student_id = student_ethnicity.student_id AND sse.ethnicity_id = student_ethnicity.ethnicity_id)

            delete: >-
              DELETE FROM student_ethnicity
                USING staging_student ss
              WHERE ss.id = student_ethnicity.student_id AND ss.deleted = 1;