DELETE FROM `staging-test`.staging_completeness WHERE id IN (-99,-98);
DELETE FROM `staging-test`.staging_administration_condition WHERE id IN (-99,-98, -97, -96);
DELETE FROM `staging-test`.staging_ethnicity WHERE id IN (-99,-98);
DELETE FROM `staging-test`.staging_gender WHERE id IN (-99,-98);
DELETE FROM `staging-test`.staging_accommodation WHERE id IN (-99,-98);
DELETE FROM `staging-test`.staging_depth_of_knowledge  WHERE id IN (-99,-98);
DELETE FROM `staging-test`.staging_math_practice  WHERE practice IN (-99,-98);
DELETE FROM `staging-test`.staging_item_trait_score WHERE id IN (-99,-98);
DELETE FROM `staging-test`.staging_target WHERE id IN (-99,-98);
DELETE FROM `staging-test`.staging_item_difficulty_cuts  WHERE id IN (-99,-98);
DELETE FROM `staging-test`.staging_claim WHERE id IN (-99,-98);
DELETE FROM `staging-test`.staging_grade WHERE id IN (-99,-98);

DELETE FROM `reporting-test`.completeness WHERE id IN (-99,-98);
DELETE FROM `reporting-test`.administration_condition WHERE id IN (-99,-98, -97, -96);
DELETE FROM `reporting-test`.ethnicity WHERE id IN (-99,-98);
DELETE FROM `reporting-test`.gender  WHERE id IN (-99,-98);
DELETE FROM `reporting-test`.accommodation WHERE id IN (-99,-98);
DELETE FROM `reporting-test`.depth_of_knowledge  WHERE id IN (-99,-98);
DELETE FROM `reporting-test`.math_practice  WHERE practice IN (-99,-98);
DELETE FROM `reporting-test`.item_trait_score WHERE id IN (-99,-98);
DELETE FROM `reporting-test`.target  WHERE id IN (-99,-98);
DELETE FROM `reporting-test`.item_difficulty_cuts  WHERE id IN (-99,-98);
DELETE FROM `reporting-test`.grade WHERE id IN (-99,-98);
DELETE FROM `reporting-test`.claim WHERE id IN (-99,-98);
