INSERT INTO reporting_test.grade (id, code, name) VALUES (-99,'AA','before test');
INSERT INTO reporting_test.completeness (id, code) VALUES (-99, 'before');
INSERT INTO reporting_test.administration_condition VALUES (-99,'before test');
INSERT INTO reporting_test.ethnicity VALUES (-99,'before test');
INSERT INTO reporting_test.gender VALUES (-99,'before test');
INSERT INTO reporting_test.accommodation VALUES(-99, 'before test');
INSERT INTO reporting_test.school_year VALUES(1999);
INSERT INTO reporting_test.claim VALUES (-99 ,2, 'claim-99', 'before test','before test');
INSERT INTO reporting_test.depth_of_knowledge  VALUES (-99, 1, 1,'before test', 'before');
INSERT INTO reporting_test.math_practice  VALUES (-99,'before test', '-9');
INSERT INTO reporting_test.item_trait_score VALUES (-99,'before test');
INSERT INTO reporting_test.target  VALUES (-99,-99,'target-99','before test');
INSERT INTO reporting_test.common_core_standard  VALUES (-99, 'naturalId-99', 1, 'before test');
INSERT INTO reporting_test.translation (namespace, label_code, language_code, label) VALUES ('backend', 'code1-test', 'lan', 'before test'),('frontend', 'fe_code1', 'lan', 'fe before test');