INSERT INTO staging_test.staging_grade (id, code, name) VALUES (-98 ,'01','First grade');
INSERT INTO staging_test.staging_completeness (id, name) VALUES (-98, 'test55');
INSERT INTO staging_test.staging_administration_condition VALUES (-98,'NS'),(-97,'SD'),(-96,'Valid');
INSERT INTO staging_test.staging_ethnicity VALUES (-98,'Asian');
INSERT INTO staging_test.staging_gender VALUES (-98,'Male');
INSERT INTO staging_test.staging_accommodation VALUES ( -98 ,'code2');
INSERT INTO staging_test.staging_claim VALUES ( -98,2,'2-W','Write Effectively','Write Effectively - ..');
INSERT INTO staging_test.staging_depth_of_knowledge  VALUES (-98,2,1,'Basic Skills and Concepts','anything');
INSERT INTO staging_test.staging_math_practice  VALUES (-98,'Reason abstractly and quantitatively');
INSERT INTO staging_test.staging_item_trait_score VALUES (-98,'Evidence/Elaboration');
INSERT INTO staging_test.staging_target VALUES (-98,-98,'10-12','WORD MEANINGS:..)');
INSERT INTO staging_test.staging_item_difficulty_cuts VALUES (-98 ,1, 2, -98,-1.51022,0.14288);
INSERT INTO staging_test.staging_language VALUES (-98,'gua');
INSERT INTO staging_test.staging_accommodation_translation VALUES (-98, -98, 'Adios');