INSERT INTO grade(id, code, sequence) VALUES (-99,'AA', 9);
INSERT INTO elas(id, code) VALUES (-99, 'before test');
INSERT INTO completeness(id, code) VALUES (-99, 'before');
INSERT INTO administration_condition(id, code) VALUES (-99,'before test');
INSERT INTO ethnicity(id, code) VALUES (-99,'before test');
INSERT INTO gender(id, code) VALUES (-99,'before test');
INSERT INTO accommodation(id, code) VALUES(-99, 'before test');
INSERT INTO school_year(year) VALUES(1999);
INSERT INTO math_practice(practice, description, code) VALUES (-99,'before test', '-9');
INSERT INTO accommodation_translation(label_code, language_code, label) VALUES ('code1-test', 'lan', 'before test');