TRUNCATE staging_completeness;
TRUNCATE staging_administration_condition;
TRUNCATE staging_ethnicity;
TRUNCATE staging_gender;
TRUNCATE staging_translation;
TRUNCATE staging_accommodation;
TRUNCATE staging_school_year;
TRUNCATE staging_depth_of_knowledge;
TRUNCATE staging_math_practice;
TRUNCATE staging_item_trait_score;
TRUNCATE staging_target;
TRUNCATE staging_common_core_standard;
TRUNCATE staging_claim;
TRUNCATE staging_grade;

DELETE FROM completeness WHERE id IN (-99,-98, -95);
DELETE FROM administration_condition WHERE id IN (-99,-98, -97, -96, -95);
DELETE FROM ethnicity WHERE id IN (-99,-98);
DELETE FROM gender  WHERE id IN (-99,-98);
DELETE FROM translation WHERE  namespace IN ('backend', 'frontend');
DELETE FROM accommodation WHERE id IN (-99,-98);
DELETE FROM school_year WHERE year IN (1999,1998);
DELETE FROM depth_of_knowledge  WHERE id IN (-99,-98);
DELETE FROM math_practice  WHERE practice IN (-99,-98);
DELETE FROM item_trait_score WHERE id IN (-99,-98);
DELETE FROM target  WHERE id IN (-99,-98);
DELETE FROM common_core_standard  WHERE id IN (-99,-98);
DELETE FROM grade WHERE id IN (-99,-98);
DELETE FROM claim WHERE id IN (-99,-98);

DELETE FROM migrate;