INSERT INTO staging_grade(id, code, name, sequence) VALUES (-98, '98', '1st-grade', 8);
INSERT INTO staging_elas(id, code) VALUES (-98, 'E98');
INSERT INTO staging_completeness(id, code) VALUES (-98, 'test55');
INSERT INTO staging_administration_condition(id, code) VALUES (-98, 'NS-test'), (-97, 'SD-test'), (-96, 'Valid-test');
INSERT INTO staging_ethnicity(id, code) VALUES (-98, 'Asian-test');
INSERT INTO staging_gender(id, code) VALUES (-98, 'Male-test');
INSERT INTO staging_accommodation(id, code) VALUES (-98, 'code2-test');
INSERT INTO staging_school_year(year) VALUES (1998);
INSERT INTO staging_math_practice(practice, description, code) VALUES (-98, 'Reason abstractly and quantitatively', '-8');
INSERT INTO staging_accommodation_translation(label_code, language_code, label) VALUES ('code2-test', 'gua', 'Adios');