INSERT INTO staging_grade (id, code, name, sequence) VALUES (-98, '98', '1st-grade', 8);
INSERT INTO staging_elas (id, code) VALUES (-98, 'E98');
INSERT INTO staging_completeness (id, code) VALUES (-98, 'test55');
INSERT INTO staging_administration_condition VALUES (-98, 'NS-test'), (-97, 'SD-test'), (-96, 'Valid-test');
INSERT INTO staging_ethnicity VALUES (-98, 'Asian-test');
INSERT INTO staging_gender VALUES (-98, 'Male-test');
INSERT INTO staging_accommodation VALUES (-98, 'code2-test');
INSERT INTO staging_school_year VALUES (1998);
INSERT INTO staging_claim VALUES (-98, 2, '2-W', 'Write Effectively', 'Write Effectively - ..');
INSERT INTO staging_depth_of_knowledge VALUES (-98, 2, 1, 'Basic Skills and Concepts', 'anything');
INSERT INTO staging_math_practice(practice, description, code) VALUES (-98, 'Reason abstractly and quantitatively', '-8');
INSERT INTO staging_item_trait_score VALUES (-98, 'Evidence/Elaboration-test');
INSERT INTO staging_target VALUES (-98, -98, 'target-98', 'WORD MEANINGS:..)');
INSERT INTO staging_common_core_standard VALUES (-98, 'naturalid-98', 2, 'standard 98');
INSERT INTO staging_translation (namespace, label_code, language_code, label) VALUES ('backend', 'code2-test', 'gua', 'Adios');