INSERT INTO staging_grade(id, code, sequence) VALUES (-99,'99', 9),(-98 ,'98',8);
INSERT INTO staging_elas(id, code) VALUES (-99, 'E99'),(-98, 'E98');
INSERT INTO staging_language(id, code, display_order, name) VALUES (-99, 'abc', 1, 'lang-abc'),(-98, 'cba', 2, 'lang-cba');
INSERT INTO staging_completeness(id, code) VALUES (-99, 'test99'), (-98, 'test98');
INSERT INTO staging_administration_condition(id, code) VALUES (-99,'99-test'),(-98,'98-test'),(-97,'97-test'),(-96,'96-test');
INSERT INTO staging_military_connected(id, code) VALUES (-99,'No-test'),(-98,'Active-test');
INSERT INTO staging_ethnicity(id, code) VALUES (-99,'AmericanIndianOrAlaskaNative-test'),(-98,'Asian-test');
INSERT INTO staging_gender(id, code) VALUES (-99,'Female-test'),(-98,'Male-test');
INSERT INTO staging_accommodation(id, code) VALUES(-99, 'code1-test'),( -98 ,'code2-test');
INSERT INTO staging_accommodation_translation (label_code, language_code, label) VALUES ('code1-test.2017', 'lan', 'Hola'),('code2-test.2017', 'gua', 'Hello');
INSERT INTO staging_school_year(year) VALUES(1999),(1998);
INSERT INTO staging_math_practice(practice, description, code) VALUES (-99,'Make sense of problems and persevere in solving them', '-9'),(-98,'Reason abstractly and quantitatively', '-8');
