INSERT INTO grade (id, code, name) VALUES (-98, '98', '1st-grade');
INSERT INTO completeness (id, code) VALUES (-98, 'test55');
INSERT INTO administration_condition VALUES (-98, 'NS-test'), (-97, 'SD-test'), (-96, 'Valid-test');
INSERT INTO ethnicity VALUES (-98, 'Asian-test');
INSERT INTO gender VALUES (-98, 'Male-test');
INSERT INTO accommodation VALUES (-98, 'code2-test');
INSERT INTO school_year VALUES (1998);
INSERT INTO claim VALUES (-98, 2, 'claim-98', 'Write Effectively', 'Write Effectively - ..');
INSERT INTO depth_of_knowledge VALUES (-98, 2, 1, 'Basic Skills and Concepts', 'anything');
INSERT INTO math_practice VALUES (-98, 'Reason abstractly and quantitatively', '-8');
INSERT INTO item_trait_score VALUES (-98, 'Evidence/Elaboration-test');
INSERT INTO target VALUES (-98, 'target-98', -98, '10-12', 'WORD MEANINGS:..)');
INSERT INTO common_core_standard VALUES (-98,'natural-98', 2, 'common core 98..)');
INSERT INTO item_difficulty_cuts (id, asmt_type_id, subject_id, grade_id, moderate_low_end, difficult_low_end) VALUES (-98, 1, 2, -98, -1.51022, 0.14288);
INSERT INTO language VALUES (-98,'gua');
INSERT INTO accommodation_translation VALUES (-98, -98, 'Adios');