INSERT INTO grade(id, code, sequence) VALUES (-98, '98', 8);
INSERT INTO elas(id, code) VALUES (-98, 'E98');
INSERT INTO completeness(id, code) VALUES (-98, 'test55');
INSERT INTO administration_condition(id, code) VALUES (-98, 'NS-test'), (-97, 'SD-test'), (-96, 'Valid-test');
INSERT INTO ethnicity(id, code) VALUES (-98, 'Asian-test');
INSERT INTO gender(id, code) VALUES (-98, 'Male-test');
INSERT INTO accommodation(id, code) VALUES (-98, 'code2-test');
INSERT INTO school_year(year) VALUES (1998);
INSERT INTO math_practice(practice, description, code) VALUES (-98, 'Reason abstractly and quantitatively', '-8');
INSERT INTO accommodation_translation(accommodation_id, language_code, label) VALUES (-98, 'gua', 'Adios');
